/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_RTMPLibTest */

#ifndef _Included_cn_dennishucd_RTMPLibTest
#define _Included_cn_dennishucd_RTMPLibTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dennishucd_RTMPLibTest
 * Method:    NativeMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_RTMPLibTest_NativeTest
  (JNIEnv *, jobject);

void InitSockets();

void CleanupSockets();


#ifdef __cplusplus
}
#endif
#endif
