/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_FFmpegAudioNative */

#ifndef _Included_cn_dennishucd_FFmpegAudioNative
#define _Included_cn_dennishucd_FFmpegAudioNative
#ifdef __cplusplus
extern "C" {
#endif


void bqPlayerCallback(SLAndroidSimpleBufferQueueItf bq, void *context);

void createEngine(JNIEnv* env, jobject obj);

void createBufferQueueAudioPlayer(JNIEnv* env, jobject obj, jint rate, jint channel, jint bitsPerSample);
/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    audioPlayer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegAudioNative_audioPlayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    audioPlayerPauseOrPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegAudioNative_audioPlayerPauseOrPlay
  (JNIEnv *, jobject);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    audioPlayerStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegAudioNative_audioPlayerStop
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
