/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_FFmpegAudioNative */

#ifndef _Included_cn_dennishucd_FFmpegAudioNative
#define _Included_cn_dennishucd_FFmpegAudioNative
#ifdef __cplusplus
extern "C" {
#endif


void bqPlayerCallback(SLAndroidSimpleBufferQueueItf bq, void *context);

void createEngine();

void createBufferQueueAudioPlayer(jint rate, jint channel, jint bitsPerSample);

static void* decodeAudio(void *arg);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    audioPlayerPauseOrPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegAudioNative_audioPlayerPauseOrPlay
  (JNIEnv *, jobject);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    audioPlayerStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegAudioNative_audioPlayerStop
  (JNIEnv *, jobject);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    setPlayingAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegAudioNative_setPlayingAudioPlayer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    setVolumeAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegAudioNative_setVolumeAudioPlayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    setMutAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegAudioNative_setMutAudioPlayer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    startAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegAudioNative_startAudioPlayer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_dennishucd_FFmpegAudioNative
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegAudioNative_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
