/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_RtmpPush */

#ifndef _Included_cn_dennishucd_RtmpPush
#define _Included_cn_dennishucd_RtmpPush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dennishucd_RtmpPush
 * Method:    pushVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_RtmpPush_pushVideo
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
