/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_FFmpegNative */

#ifndef _Included_cn_dennishucd_FFmpegNative
#define _Included_cn_dennishucd_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegNative_avcodec_1find_1decoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    naInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegNative_naInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cn_dennishucd_FFmpegNative_naGetVideoRes
  (JNIEnv *, jobject);

/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    naSetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_FFmpegNative_naSetup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    naPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_dennishucd_FFmpegNative_naPlay
  (JNIEnv *, jobject);

  jobject createBitmap(JNIEnv *pEnv, jint pWidth, jint pHeight);
    void SaveFrame(JNIEnv *pEnv, jobject pBitmap, jint width, jint height);
    static jint decodeVideo();

#ifdef __cplusplus
}
#endif
#endif
