/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_ThreadInJava */

#ifndef _Included_cn_dennishucd_ThreadInJava
#define _Included_cn_dennishucd_ThreadInJava
#ifdef __cplusplus
extern "C" {
#endif

jobject createBitmapFromJni(JNIEnv *pEnv, jint pWidth, jint pHeight);
/*
 * Class:     cn_dennishucd_ThreadInJava
 * Method:    nativePlay
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_dennishucd_ThreadInJava_nativePlay
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
